version: "3"
services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=password"
volumes:
  postgres-data:
